# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analyzer_pb2 as analyzer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analyzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyzerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/analyzer.AnalyzerService/Analyze',
                request_serializer=analyzer__pb2.NumberRequest.SerializeToString,
                response_deserializer=analyzer__pb2.NumberResponse.FromString,
                _registered_method=True)
        self.StreamFactors = channel.unary_stream(
                '/analyzer.AnalyzerService/StreamFactors',
                request_serializer=analyzer__pb2.NumberRequest.SerializeToString,
                response_deserializer=analyzer__pb2.FactorResponse.FromString,
                _registered_method=True)
        self.ExplainText = channel.unary_stream(
                '/analyzer.AnalyzerService/ExplainText',
                request_serializer=analyzer__pb2.TextRequest.SerializeToString,
                response_deserializer=analyzer__pb2.TextChunk.FromString,
                _registered_method=True)


class AnalyzerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFactors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyzerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=analyzer__pb2.NumberRequest.FromString,
                    response_serializer=analyzer__pb2.NumberResponse.SerializeToString,
            ),
            'StreamFactors': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFactors,
                    request_deserializer=analyzer__pb2.NumberRequest.FromString,
                    response_serializer=analyzer__pb2.FactorResponse.SerializeToString,
            ),
            'ExplainText': grpc.unary_stream_rpc_method_handler(
                    servicer.ExplainText,
                    request_deserializer=analyzer__pb2.TextRequest.FromString,
                    response_serializer=analyzer__pb2.TextChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyzer.AnalyzerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analyzer.AnalyzerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyzerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analyzer.AnalyzerService/Analyze',
            analyzer__pb2.NumberRequest.SerializeToString,
            analyzer__pb2.NumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFactors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/analyzer.AnalyzerService/StreamFactors',
            analyzer__pb2.NumberRequest.SerializeToString,
            analyzer__pb2.FactorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/analyzer.AnalyzerService/ExplainText',
            analyzer__pb2.TextRequest.SerializeToString,
            analyzer__pb2.TextChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
